### ISSUE TITLE
is it possible to assign channels higher than N°8 in bluetooth.

### ISSUE THREAD

**Issue by samsab1** [dlktdr/HeadTracker#175] opened 2024-07-29 16:19 UTC
is it possible to assign channels higher than N°8 in bluetooth.

will there be a new version allowing it.
otherwise it requires a thorough review of the mixes and settings of our models using this headtracker, while it would be simpler to integrate channels 12,13,14 for example in training by bluetooth

**Comment by dlktdr** [comment] 2024-07-30 22:37
Short answer, not easy. No plans to support it. 

Duplicate of #148.

**Closed by dlktdr** 2024-07-30 22:37 UTC
